#!/bin/bash
#wgetseed $profondeurDossier $critere1 $critere2 $dossier
#TODO pb de parsing avec &#32; IFS et eval ??
#TODO lorsque autoDl est actif et que la ligne courante est un dossier le script cherche les élements restants de la liste dans ce dossier (i+1) 
#server adress here
#site="ftp://dns.adress.org//data"
site="ftp://cluster1m.seedbox.fr//data/complete/"
triHTML="sed 's/%20/ /g' | sed 's/%C3%A9/é/g' | sed 's/%C3%B4/ô/g' | sed 's/%5B/[/g' | sed 's/%26/\&/g' | sed 's/%5D/]/g' | sed 's/(/\\(/g' | sed 's/)/\\)/g' | sed 's/%C3%A0/à/g' | sed 's/%C3%A8/è/g' | sed 's/%E2%80%99/ /g' | sed 's/%C3%AA/ê/g' | sed 's/%2C/,/g' | sed 's/%C3%B5/õ/g' | sed 's/%C3%A7/ç/g' | sed 's/%2B/+/g' | sed 's/%C3%BB/û/g' | sed 's/%40/@/g'" 
triHTMLInverse="sed 's/\&\#32 /%20/g' | sed 's/ /%20/g' | sed 's/\&\#32\;/%20/g'"
chemin="/tmp/.wgetseed"
resultatsSeed="$chemin/resultatsSeed"
listeFilms="$chemin/listeFilms"
nomsNoHtml="$chemin/nomsNoHtml"
resultatsSeedComplet="$chemin/resultatsSeedComplet"
resultatsSeedDossier="$chemin/resultatsSeedDossier"
typeConnexion="--secure-protocol=TLSv1_3"
ecraser=false

#TODO creer l'arborescence
#TODO Téléchargement automatique lorsque plusieurs dossiers dans les résultats
#TODO PB parfois télécharge en double

effacer(){
    rm -r "$chemin" > /dev/null 2>&1
}

test(){
    echo ""; echo ""$'\e[1;36m'"i : $1 | crit1 : $2 | crit2 : $3 | dlAuto : $4 | dossier : $5 "$'\e[0m'""
}

telecharger(){
    #$1 nom #$2 dossier 
    local nomSysteme=$(echo "$1" | eval $triHTML)
    local telechargement=true
    # Verification si le fichier existe déjà    
    # TODO verifier que les fichiers font la meme taille
    for liste in $(ls); do
	if [ "$liste" == "$nomSysteme" ]; then
            if [[ "$ecraser" == "true" ]]; then # || $reponse =~ ^[YyOo]$ ]]; then
                rm "$nomSysteme"
                break
            else
		echo "Fichier déjà présent"
		telechargement=false
	    fi
        fi
    done
    if [ "$telechargement" = true ]; then
        # wget $site$2$1 $typeConnexion
        curl $site$2$1
    fi
}


wgetseed()
{   test $1 $2 $3 $4 $5 $6
    local iteration=$1
    local critere1=$2
    local critere2=$3
    local dlAuto=$4
    local dossier=$(echo "$5" | sed 's/\/\/$/\//g')
    local fichier=$(echo "$5$6" | sed 's/[^a-zA-Z0-9_]//g'); # echo "fichier = $fichier"
    local colonne=$((4+$iteration)) # Passé de $((4+$iteration)) à 5 du passage de mint à debian 11 (version wget ?/pas la meme reponse du serveur)

    if [ "$critere1" == "." -a "$iteration" -ne 0 ]; then
        local critere1=""
    fi
    if [ "$critere2" == "." -a "$iteration" -ne 0 ]; then
        local critere2=""
    fi
    if [ "$dossier" == "." ]; then
        local dossier=""
    fi
    
    # Requete
    # wget -O - $site$dossier $typeConnexion --quiet > "$listeFilms$fichier"
    curl -n $site$dossier > "$listeFilms$fichier"
    cat "$listeFilms$fichier"
    
    # Récupérer les lignes qui concernent les dossiers et fichiers
    if [ "$critere1" == "" ]; then
        cat "$listeFilms$fichier" | grep "^d\|^-" > "$resultatsSeedComplet$fichier"
    elif [ "$critere2" == "" ]; then
        cat "$listeFilms$fichier" | grep -i "$critere1" | grep "^d\|^-" > "$resultatsSeedComplet$fichier"
    else
        cat "$listeFilms$fichier" | grep -i -E "$critere1.*$critere2" | grep "^d\|^-" > "$resultatsSeedComplet$fichier"
    fi

    cat "$resultatsSeedComplet$fichier"

    # Récupérer les noms de dossiers ou fichiers
    cat "$listeFilms$fichier" | cut -d " " -f 9 > "$resultatsSeed$fichier"
    cat "$resultatsSeed$fichier"
    # Parsing % characters
    cat "$resultatsSeed$fichier" | eval $triHTML > "$nomsNoHtml$fichier"
    local nbLignes=$(cat "$resultatsSeed$fichier" | wc -l)
    # Affichage résultats recherche
    echo "";cat "$nomsNoHtml$fichier"
    
    if [[ $nbLignes == 1 ]]; then
        if [ $(cat $resultatsSeedComplet$fichier  | cut -d "/" -f 1 | grep "Fichier") ]; then
            local nom=$(cat "$resultatsSeed$fichier")
            local nomNoHtml=$(echo "$nom" | eval $triHTML)
            if $dlAuto; then
                telecharger $nom $dossier
            else 
                read -p "Voulez-vous télécharger \"$nomNoHtml\" : " -n 1 -r
                echo ""
                if [[ $REPLY =~ ^[YyOo]$ ]]; then
                    telecharger $nom $dossier
                fi
            fi
        elif [ $(cat $resultatsSeedComplet$fichier | cut -d "/" -f 1 | grep "Répertoire") ]; then
            local nom=$(cat $resultatsSeedComplet$fichier | cut -d "/" -f $colonne | cut -d "\"" -f 1)
            local nomNoHtml=$(echo "$nom" | eval $triHTML)
            local critere1="."
            local critere2="."
            # echo "resultat parse nom = $nom" # todo
            # if [ "$nom" != "" ]; then
            #     local dossier="$dossier$nom/"
            # fi
            wgetseed $((1+$iteration)) $critere1 $critere2 $dlAuto "$dossier$nom/" $nom
        fi
    elif [ $nbLignes -eq 0 ]; then
        echo  "Pas de résultat pour "$'\e[1;31m'"\"$critere1 $critere2\""$'\e[0m'
    else
        if $dlAuto; then
            local ligne
            while read ligne; do
                if [ "$ligne" != "" ]; then
                    local nom=$(echo "$ligne" | cut -d "/" -f $colonne | cut -d "\"" -f 1)
                    local critere1="."
                    local critere2="."
                    # echo "resultat parse nom = $nom" # todo
                    if [ $(echo "$ligne" | grep "Répertoire") ]; then
                        wgetseed $((1+$iteration)) $critere1 $critere2 $dlAuto "$dossier$nom/" $nom
                    else
                        if [ "$dossier" == "" ]; then
                            local dossier="."
                        fi
                        wgetseed $iteration $nom $critere2 $dlAuto $dossier $nom

                    fi
                fi
            done < "$resultatsSeedComplet$fichier"
        else
            echo ""; read -p "Voulez-vous tout télécharger ? : " -n 1 -r
            if [[ $REPLY =~ ^[YyOo]$ ]]; then
                if [ "$critere1" == "" ]; then
                        local critere1="."
                fi
                if [ "$critere2" == "" ]; then
                        local critere2="."
                fi
                wgetseed $iteration $critere1 $critere2 true $dossier
            else
                echo ""; read -p "Saisissez le 2eme critère parmi la liste : "
                for crit2 in $REPLY; do
                    local crit2=$(echo "$crit2" | eval $triHTMLInverse)
                    if [ "$critere1" == "" ]; then
                        local critere1="."
                    fi
                    wgetseed $iteration $crit2 $critere1 $dlAuto $dossier
                done 
            fi
        fi
    fi
}
SAVEIFS=$IFS
IFS=$(echo -en "\b\n~")
effacer
mkdir $chemin
read -p "Voulez-vous écraser automatiquement le.s fichier.s ? : " -n 1 -r; echo ""
if [[ $REPLY =~ ^[YyOo]$ ]]; then
    ecraser=true
fi
recherche=$1
if [ "$recherche" == "" ]; then
    recherche="."
fi
wgetseed 1 $recherche "." false
effacer
IFS=$SAVEIFS
